GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6451e718c75dbca140e35059

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Harry Potter",
  "subscriberToChannel": "Hogwarts School daily news "
}









